/**
 * NATS subjects for the track processing pipeline.
 * Covers the full lifecycle: upload, fingerprinting (Petrified),
 * transcription (Fort Minor), reasoning (Stereo), transcoding
 * (Mockingbird), and HLS persistence (Hybrid Storage).
 */
export enum TrackEvent {
  /** Upload received by Soundgarden (Backstage observes). */
  UploadReceived = 'track.upload.received',
  /** Upload validated by Soundgarden (Backstage observes). */
  UploadValidated = 'track.upload.validated',
  /** Upload stored to object storage by Soundgarden (Backstage observes). */
  UploadStored = 'track.upload.stored',
  /** Upload fully completed -- triggers Petrified fingerprinting (consumed by Petrified, Backstage). */
  Uploaded = 'track.uploaded',
  /** Upload failed (Backstage observes). */
  UploadFailed = 'track.upload.failed',

  /** Fingerprint generated by Petrified (consumed by Fort Minor, Stereo, Backstage). */
  PetrifiedGenerated = 'track.petrified.generated',
  /** Song identified by Petrified (Backstage observes). */
  PetrifiedSongFound = 'track.petrified.song.found',
  /** Song not found in fingerprint DB (Backstage observes). */
  PetrifiedSongUnknown = 'track.petrified.song.unknown',
  /** Fingerprint detected/matched (Backstage observes). */
  PetrifiedDetected = 'track.petrified.detected',
  /** Fingerprinting failed (Backstage observes). */
  PetrifiedFailed = 'track.petrified.failed',
  /** Duplicate track detected by Petrified (Backstage observes). */
  DuplicateDetected = 'track.duplicate.detected',

  /** Transcription started by Fort Minor (Backstage observes). */
  FortMinorStarted = 'track.fort-minor.started',
  /** Transcription completed by Fort Minor (consumed by Stereo, Backstage). */
  FortMinorCompleted = 'track.fort-minor.completed',
  /** Transcription failed (Backstage observes). */
  FortMinorFailed = 'track.fort-minor.failed',

  /** AI reasoning started by Stereo (Backstage observes). */
  StereoStarted = 'track.stereo.started',
  /** Track approved by Stereo (consumed by Mockingbird, Backstage). */
  Approved = 'track.approved',
  /** Track rejected by Stereo (Backstage observes). */
  Rejected = 'track.rejected',
  /** AI reasoning failed (Backstage observes). */
  StereoFailed = 'track.stereo.failed',

  /** Transcoding started by Mockingbird (Backstage observes). */
  TranscodingStarted = 'track.transcoding.started',
  /** Transcoding completed by Mockingbird (Backstage observes). */
  TranscodingCompleted = 'track.transcoding.completed',
  /** Transcoding failed (Backstage observes). */
  TranscodingFailed = 'track.transcoding.failed',

  /** HLS package generated by Mockingbird (consumed by Hybrid Storage, Backstage). */
  HlsGenerated = 'track.hls.generated',
  /** HLS package persisted by Hybrid Storage (Backstage observes). */
  HlsStored = 'track.hls.stored',
  /** HLS generation/persistence failed (Backstage observes). */
  HlsFailed = 'track.hls.failed'
}
